name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - run: node --version
      - run: npm --version
      - name: Change to root directory
        run: |
          ls -la 
      - uses: actions/setup-node@v3
        with:
              persist-credentials: false
      - run: npm install
      - run: node index.js
